### ISSUE TITLE
dedicated crouch buttons

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#42]
- [x] toggle half-crouch (1964 behavior) - implemented by #184
- [x] toggle full-crouch (1964 behavior)  - implemented by #184
- [x] cycle crouch (xbla L3 behavior)  - implemented by #184
- [ ] implement hold / toggle flag per/player for 1964-style bindings

**Comment by cylonicboom** [comment]
This is partially implemented as part of #184
